version: '3'

volumes:
  db:

services:
  db:
    image: postgres:10
    volumes:
      - 'db:/var/lib/postgresql/data'
    environment:
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"

  app:
    build: .
    env_file:
      - dev.env
    depends_on:
      - db
    working_dir: /app
